spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///oj?characterEncoding=utf8
  jpa:
    show-sql: true
server:
  context-path: /oj
logging:
  file: d:/oj.log